### PR TITLE
Fix `updateStatus` doesn't update replication when read-only mode

### LINKED ISSUE #360: Cannot update status of writable/replicating
Changing the status to `false` by the following command:
```
curl -v -X PATCH http://your-centraldogma-domain/api/v1/status -H'authorization: bearer appToken-******' -H'Content-Type:application/json-patch+json' -d'[{"op":"replace","path":"/writable","value":false}, {"op":"replace","path":"/replicating","value":false}]'
```
Then, the following command doesn't work:
```
curl -v -X PATCH http://your-centraldogma-domain/api/v1/status -H'authorization: bearer appToken-******' -H'Content-Type:application/json-patch+json' -d'[{"op":"replace","path":"/writable","value":true}, {"op":"replace","path":"/replicating","value":true}]'
```

Also,`304 Not Modified` is returned when trying to change `/replicating` only.

### PR DESCRIPTION
**Pull request by ghkim3221**
### Motivation

 - #360

### Modification

 - Enable replication when read-only with not-replication mode and given `replicating` is `true`.
 - Disable replication when read-only with replication mode and given `replicating` is `false`.

### Result

 - Fix #360 (?)
 - Users can enable/disable replication when read-only mode.

### CODE REVIEW

File: server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java [hunk 1]
```diff
@@ -124,6 +124,28 @@ public ServerStatus status() {
...
+        } else if (replicating) { // unreplicating -> replicating
+            logger.warn("Enabling replication with read-only mode");
+            return executor().start().handle((unused, cause) -> {
+                if (cause != null) {
+                    logger.warn("Failed to start the command executor:", cause);
+                } else {
+                    logger.info("Enabled replication");
+                }
+                return status();
+            });
```
Comment (ikhoon) [inline server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java:148]: Could we simplify this if-else chains? For example:
```java
if (oldStatus.writable != writable) {
     executor().setWritable(writable);
}
if (oldStatus.replicating != replicating) {
   if (replicating) {
        // log
        executor().start().handle(...);
   } else {
        // log
        executor().stop().handle(...);
   }
}
```

Comment (ikhoon) [reply server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java:148]: Otherwise, extract common code to template methods?

File: server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java [hunk 2]
```diff
@@ -124,6 +124,28 @@ public ServerStatus status() {
                 }
                 return status();
             });
+        } else if (oldStatus.replicating) {
```
Comment (minwoox) [inline server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java:127]: How about adding a comment that describes the status change?
```
//    writable       replicating      result
//----------------------------------------------------------------------- 
//    true -> true                    not_modified exception
//-----------------------------------------------------------------------
//    true -> false  true -> true     setWritable(false)
//                   true -> false    setWritable(false) & Stop executor.
//-----------------------------------------------------------------------
//    false -> true  true -> true     setWritable(true)
//                   false -> true    setWritable(true) & start executor.
//-----------------------------------------------------------------------
//    false -> false true -> false    Stop executor.
//                   false -> true    Start executor.
```
And I think if we implement the logic in that way we can use the early return style and also we are not going to miss any cases.
Currently, I think we missed the fourth case which is `false -> true |  true -> true  |   setWritable(true)`.
Also, it would be nice if we add:
```
if (oldStatus.writable == writable && oldStatus.replicating == replicating) {
    throw HttpStatusException.of(HttpStatus.NOT_MODIFIED);
}
```

File: server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java (hunk 1 above)
Comment (ghkim3221) [reply server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java:148]: I added tailing else-if because of the more specific logging messages (such as _with replication enabled_ or with _read-only mode_). I agree that we need simplification. If we can give up the messages, let me simplify.

> extract common code to template methods?

May I ask what _template methods_ means?

File: server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java [hunk 3]
```diff
@@ -88,45 +88,61 @@ public ServerStatus status() {
...
+        if (oldStatus.writable == writable && oldStatus.replicating == replicating) {
+            throw HttpStatusException.of(HttpStatus.NOT_MODIFIED);
+        }
+
+        if (oldStatus.writable != writable) {
+            executor().setWritable(writable);
+            if (writable) {
+                logger.warn("Left read-only mode");
+            } else {
+                logger.warn("Entered read-only mode");
```
Comment (ikhoon) [inline server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java:119]:
```suggestion
                logger.warn("Left read-only mode. replication: {}, replicating");
            } else {
                logger.warn("Entered read-only mode. replication: {}, replicating");
```

**Review by ikhoon — APPROVED** [review]
Looks good to me! 💯

File: server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java [hunk 4]
```diff
@@ -88,45 +88,61 @@ public ServerStatus status() {
...
                                              "'replicating' must be 'true' if 'writable' is 'true'.");
         }
+        if (oldStatus.writable == writable && oldStatus.replicating == replicating) {
+            throw HttpStatusException.of(HttpStatus.NOT_MODIFIED);
+        }
+
+        if (oldStatus.writable != writable) {
+            executor().setWritable(writable);
+            if (writable) {
+                logger.warn("Left read-only mode. replication: {}, replicating");
```
Comment (minwoox) [inline server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java:117]: nit:
```suggestion
                logger.warn("Left read-only mode. replication: {}", replicating);
```

File: server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java [hunk 5]
```diff
@@ -88,45 +88,61 @@ public ServerStatus status() {
...
+            } else {
+                logger.warn("Entered read-only mode. replication: {}, replicating");
```
Comment (minwoox) [inline server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java:119]: nit:
```suggestion
                logger.warn("Entered read-only mode. replication: {}", replicating);
```

File: server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java [hunk 6]
```diff
@@ -88,45 +88,61 @@ public ServerStatus status() {
...
+                });
+            } else {
+                return executor().stop().handle((unused, cause) -> {
+                    if (cause != null) {
+                        logger.warn("Failed to stop the command executor:", cause);
+                    } else {
+                        logger.info("Disabled replication");
+                    }
+                    return status();
+                });
```
Comment (minwoox) [inline server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java:141]: nit: we can return early.
```suggestion
            }
            return executor().stop().handle((unused, cause) -> {
                if (cause != null) {
                    logger.warn("Failed to stop the command executor:", cause);
                } else {
                    logger.info("Disabled replication");
                }
                return status();
            });
```

**Review by minwoox — APPROVED** [review]
This really looks awesome. 👍 
Thanks a lot!

File: server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java (hunk 4 above)
Comment (ghkim3221) [reply server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java]: 😱

File: server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java [hunk 7]
```diff
@@ -88,45 +88,60 @@ public ServerStatus status() {
...
-                        } else {
-                            logger.info("Entered read-only mode with replication disabled");
-                        }
-                        return status();
-                    });
-                }
+        if (oldStatus.writable != writable) {
+            executor().setWritable(writable);
+            if (writable) {
+                logger.warn("Left read-only mode.");
```
Comment (ghkim3221) [inline server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java:117]: Removed `replication` because always true in this case.

File: server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java (hunk 5 above)
Comment (ikhoon) [reply server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java]: 😱

**Comment by minwoox** [comment]
Awesome! 🎉 🎉 🎉 
I can't wait to see your next PR. 😆
