### PR TITLE
Retry client requests on replication lag

### LINKED ISSUE #435: Make Java client tolerant to replication lag
A client sometimes gets different entries from different replicas in the same Central Dogma cluster, mainly due to replication lag, i.e. Even if you learned that the latest revision of a repository in replica A is 42, you may fail to get a file at revision 42 from replica B.

Currently, in such a case, our Java client simply fails with `RevisionNotFoundException`, which is confusing to our users.

We could instead keep the latest known revision numbers of the repositories and retry a few more times when it is certain that a `RevisionNotFoundException` was raised due to the replication lag.

For Go client: https://github.com/line/centraldogma-go/issues/38

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

A client sometimes gets different entries from different replicas in the
same Central Dogma cluster, mainly due to replication lag, i.e. Even if
you learned that the latest revision of a repository in replica A is 42,
you may fail to get a file at revision 42 from replica B.

Currently, in such a case, our Java client simply fails with
`RevisionNotFoundException`, which is confusing to our users.

We could instead keep the latest known revision numbers of the
repositories and retry a few more times when it is certain that a
`RevisionNotFoundException` was raised due to the replication lag.

Modifications:

- Make all shortcut methods in `CentralDogma` final in
  `AbstractCentralDogma` so that a dev can focus on less number of
  methods.
- Add `ReplicationLagTolerantCentralDogma`
- Add the properties related with replication lag tolerance to
  `AbstractCentralDogmaBuilder`:
  - `maxRetriesOnReplicationLag`
  - `retryIntervalOnReplicationLag`

Result:

- Replication lag is detected and the request is retried automatically.
- Fixes #435

### CODE REVIEW

**Comment by jiao-zhangS** [comment]
LGTM

File: client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaBuilder.java [hunk 1]
```diff
@@ -60,7 +63,15 @@ public CentralDogma build() throws UnknownHostException {
             }
             return delegate.execute(ctx, req);
         });
-        return new LegacyCentralDogma(clientFactory().eventLoopGroup(),
-                                      builder.build(CentralDogmaService.AsyncIface.class));
+
+        final EventLoopGroup executor = clientFactory().eventLoopGroup();
+        final int maxRetriesOnReplicationLag = maxNumRetriesOnReplicationLag();
+        final CentralDogma dogma = new LegacyCentralDogma(executor, builder.build(AsyncIface.class));
+        if (maxRetriesOnReplicationLag <= 0) {
```
Comment (jiao-zhangS) [inline client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaBuilder.java]: is it possible that maxRetriesOnReplicationLag < 0 ?
maxNumRetriesOnReplicationLag(int maxRetriesOnReplicationLag) already checked the augment.

Comment (trustin) [reply client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaBuilder.java]: It's not possible but I just wanted to be as defensive as possible. :-)

Comment (jiao-zhangS) [reply client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaBuilder.java]: oh, I see

File: client/java/src/main/java/com/linecorp/centraldogma/internal/client/ReplicationLagTolerantCentralDogma.java [hunk 2]
```diff
@@ -0,0 +1,485 @@
...
+                                    return false;
+                                }
+                                final Revision normRev = normFromRev.compareTo(normToRev) > 0 ? normFromRev
+                                                                                              : normToRev;
+                                return handleRevisionNotFound(projectName, repositoryName, normRev, cause);
+                            });
+                });
+    }
+
+    private <T> CompletableFuture<T> execute(
```
Comment (ikhoon) [inline client/java/src/main/java/com/linecorp/centraldogma/internal/client/ReplicationLagTolerantCentralDogma.java]: nit: Even though this is a private method, in my case, I'm a little confused on this method name.
How about renaming `execute(...)` to `excuteWithRetry(...)`?

Comment (trustin) [reply client/java/src/main/java/com/linecorp/centraldogma/internal/client/ReplicationLagTolerantCentralDogma.java]: Renamed to `executeWithRetries()` and added some Javadoc for clarity.

File: client/java/src/main/java/com/linecorp/centraldogma/internal/client/ReplicationLagTolerantCentralDogma.java [hunk 3]
```diff
@@ -0,0 +1,485 @@
...
+    public CompletableFuture<Void> unremoveRepository(String projectName, String repositoryName) {
+        return delegate.unremoveRepository(projectName, repositoryName);
+    }
+
+    @Override
+    public CompletableFuture<Map<String, RepositoryInfo>> listRepositories(String projectName) {
+        return execute(
+                () -> delegate.listRepositories(projectName),
+                (res, cause) -> {
+                    for (RepositoryInfo info : res.values()) {
```
[the remark this answers is not in the document]
Comment (trustin) [reply client/java/src/main/java/com/linecorp/centraldogma/internal/client/ReplicationLagTolerantCentralDogma.java]: Oops! Thanks :pray:
