### PR TITLE
Fix a bug where illegal context is pushed

### LINKED ISSUE #544: Should fix `IllegalContextPushingException`
```java
java.lang.IllegalStateException: Trying to call object wrapped with context ............ This means the callback was called from unexpected thread or forgetting to close previous context.
	at com.linecorp.armeria.internal.common.RequestContextUtil.newIllegalContextPushingException(RequestContextUtil.java:137)
	at com.linecorp.armeria.server.ServiceRequestContext.push(ServiceRequestContext.java:230)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.convertResponse(AnnotatedService.java:373)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.lambda$serve0$5(AnnotatedService.java:295)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:604)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture.unipush(CompletableFuture.java:589)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:660)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at com.linecorp.centraldogma.server.internal.api.ContentServiceV1.getDiff(ContentServiceV1.java:364)
	at jdk.internal.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.invoke(AnnotatedService.java:323)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.lambda$serve0$4(AnnotatedService.java:288)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.serve0(AnnotatedService.java:288)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.serve(AnnotatedService.java:251)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.serve(AnnotatedService.java:84)
	at com.linecorp.centraldogma.server.internal.api.auth.RequiresPermissionDecorator.lambda$serveUserRepo$1(RequiresPermissionDecorator.java:122)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:946)
	at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2266)
	at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:143)
	at com.linecorp.centraldogma.server.internal.api.auth.RequiresPermissionDecorator.serveUserRepo(RequiresPermissionDecorator.java:111)
	at com.linecorp.centraldogma.server.internal.api.auth.RequiresPermissionDecorator.serve(RequiresPermissionDecorator.java:70)
	at com.linecorp.centraldogma.server.internal.api.auth.RequiresPermissionDecorator.serve(RequiresPermissionDecorator.java:48)
	at com.linecorp.centraldogma.server.metadata.MetadataServiceInjector.serve(MetadataServiceInjector.java:58)
	at com.linecorp.centraldogma.server.metadata.MetadataServiceInjector.serve(MetadataServiceInjector.java:35)
	at com.linecorp.armeria.server.auth.AuthService.lambda$serve$0(AuthService.java:93)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:479)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### PR DESCRIPTION
**Pull request by minwoox**
Motivation:
Illegal context is pushed when the future is complete by the `CachingRepository`.

Modification:
- Use `handleAsync` with `ctx.eventLoop()` for the future that is complete by the `CachingRepository`.

Result:
- You no longer see `IllegalStateException` by pushing the wrong context.
- Fix #544

### CODE REVIEW

**Comment by ikhoon** [comment]
Question: Do we refactor `RepositoryCache` to run the returned future executed in non context-aware executor?
For example:
```diff
public class RepositoryCache {

+    private Executor executor() {
+        return RequestContext.mapCurrent(RequestContext::eventLoop, CommonPools.workerGroup()::next);
+    }
+
     public <T> CompletableFuture<T> get(CacheableCall<T> call) {
         requireNonNull(call, "call");
         @SuppressWarnings("unchecked")
         final CompletableFuture<T> f = (CompletableFuture<T>) cache.get(call);
-        return f;
+        return f.thenApplyAsync(Function.identity(), executor());
     }
}
```

**Comment by minwoox** [comment]
@ikhoon That's a good suggestion. 👍  Let me use that.

File: server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepository.java [hunk 1]
```diff
@@ -220,6 +246,32 @@ public Author author() {
...
+
+        return Repository.super.mergeFiles(normalizedRevision, query).thenApply(mergedEntry -> {
+            key.computedValue(mergedEntry);
+            cache.get(key);
+            return mergedEntry;
+        });
+    }
+
+    private static Executor executor() {
+        return RequestContext.mapCurrent((RequestContext::eventLoop), CommonPools.workerGroup()::next);
```
Comment (ikhoon) [inline server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepository.java:272]: nit:
```suggestion
        return RequestContext.mapCurrent(RequestContext::eventLoop, CommonPools.workerGroup()::next);
```

**Review by ikhoon — APPROVED** [review]
Thanks! @minwoox

File: server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepository.java (hunk 1 above)
Comment (minwoox) [reply server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepository.java]: 😅

**Comment by minwoox** [comment]
Thanks for reviewing. 😉
