### PR TITLE
Make a server unhealthy when it is about to shut down.

### LINKED ISSUE #704: Unwrap exception in the client
We have pre-defined exceptions and throw them in the client depending on the response the client gets.
For example, if the client gets a shutting down exception message from the server, the client throws `ShuttingDownException`.
However, the error message from the server isn't unwrapped so `CentralDogmaException` is thrown instead:
```
com.linecorp.centraldogma.common.CentralDogmaException: unexpected response: [:status=500, ...], {"exception":"java.util.concurrent.CompletionException","message":"com.linecorp.centraldogma.common.ShuttingDownException"}
 at com.linecorp.centraldogma.client.armeria.ArmeriaCentralDogma.handleErrorResponse(ArmeriaCentralDogma.java:1135)
 at com.linecorp.centraldogma.client.armeria.ArmeriaCentralDogma.normalizeRevision(ArmeriaCentralDogma.java:396)
 at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
 at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
 at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
 at com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:152)
 at com.linecorp.armeria.common.util.UnmodifiableFuture.lambda$wrap$0(UnmodifiableFuture.java:103)
```
We should unwrap the message and throw the corresponding exception.
https://github.com/line/centraldogma/blob/master/client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogma.java#L1116-L1135

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

If a server stops, it closes the internal resources first and finally stops Armeria server. Since there is no custom `HealthChecker` specified, the status of the server becomes unhealthy when Armeria server starts to shut down. Meanwhile, clients try to send new requests to the closing server which get `ShuttingDownException`s.

I also found that a `CompletionException` is not properly peeled when an `HttpResponse` is created by `HttpApiUtil`.
```
com.linecorp.centraldogma.common.CentralDogmaException: unexpected response: [:status=500, content-type=application/json; charset=utf-8, ...]
   {"exception":"java.util.concurrent.CompletionException","message":"com.linecorp.centraldogma.common.ShuttingDownException"}
	at com.linecorp.centraldogma.client.armeria.ArmeriaCentralDogma.handleErrorResponse(ArmeriaCentralDogma.java:1135)
	at com.linecorp.centraldogma.client.armeria.ArmeriaCentralDogma.normalizeRevision(ArmeriaCentralDogma.java:396)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
```

Modifications:

- Add a `SettableHealthChecker` which becomes healthy when an Armeria server is completely started and becomes unhealthy when a Central Dogma server is about to close.
- Peel an exception before it is converted to an `HttpResponse` in `HttpApiUtil`.

Result:
- Close #704
- You will no longer see `ShuttingDownException` warning messages.

### CODE REVIEW

File: server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java [hunk 1]
```diff
@@ -359,6 +362,7 @@ private void doStart() throws Exception {
             server = startServer(pm, executor, meterRegistry, sessionManager);
             logger.info("Started the RPC server at: {}", server.activePorts());
             logger.info("Started the Central Dogma successfully.");
+            serverHealth.setHealthy(true);
```
Comment (minwoox) [inline server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java:365]: nit: better to set this at line 369?
```java
if (success) {
  serverHealth.setHealthy(true);
  this.repositoryWorker = repositoryWorker;
  ...
}
```

**Review by minwoox — APPROVED** [review]
Just one nit. Thanks!

**Review by jrhee17 — APPROVED** [review]
Thanks @ikhoon ! 🙇 👍 🙇

File: server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java (hunk 1 above)
Comment (ikhoon) [reply server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java:365]: Better!

**Comment by minwoox** [comment]
Nice work, @ikhoon! 👍
