### PR TITLE
Do not list partially-created projects unless necessary

### LINKED ISSUE #245: Do not stop mirroring scheduler
I have no idea why `meta` repository didn't exist at that time. Anyway it would be better that we make the mirroring scheduler not stopped even when an exception is raised during scheduling mirroring job.

```
[ERROR](c.l.c.s.i.m.DefaultMirroringService) [mirroring-scheduler-6-1] Git-to-CD mirroring scheduler stopped due to an unexpected ex
ception:
com.linecorp.centraldogma.common.RepositoryNotFoundException: meta
    at com.linecorp.centraldogma.server.internal.storage.repository.RepositoryManagerWrapper.get(RepositoryManagerWrapper.java:66)
    at com.linecorp.centraldogma.server.internal.storage.repository.RepositoryManagerWrapper.get(RepositoryManagerWrapper.java:36)
    at com.linecorp.centraldogma.server.internal.storage.project.DefaultProject.metaRepo(DefaultProject.java:78)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at com.linecorp.centraldogma.server.internal.mirror.DefaultMirroringService.schedulePendingMirrors(DefaultMirroringService.java:185)
    at com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask.run(MoreExecutors.java:630)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

When we access a project, we usually assume that `dogma` and `meta`
repositories exist in that project. However, the creation of a project
is a multi-step process:

- Create a project
- Create the `dogma` repository
- Create the `meta` repository

Therefore, if another party who attempts to access the project (or its
`meta` repository) at the same time, he or she may see a partial view of
the project.

Modifications:

- Move the creation of `dogma` and `meta` repository to `DefaultProject`
  so that a project creation is fully transactional and thus a failed
  project creation will roll back the partial changes.
  - `ProjectInitializingCommandExecutor` is gone.
- Modify `StorageManager.create()` so that the storage subsystems can
  record the creation time and project author correctly.
- Miscellaneous:
  - Replace `INTERNAL_REPO` and `METADATA_REPO` with `Project.REPO_DOGMA`
  - Prevent API callers from creating `meta` or `dogma` repository,
    because they must be created by the system when a project is created.

Result:

- Nobody can see a partially created project.
- Fixes #245

### CODE REVIEW

File: server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaServiceImpl.java [hunk 1]
```diff
@@ -150,6 +151,11 @@ public void listRemovedProjects(AsyncMethodCallback resultHandler) {
     @Override
     public void createRepository(String projectName, String repositoryName,
                                  AsyncMethodCallback resultHandler) {
+        // HTTP v1 API will return '403 forbidden' in this case, but we deal it as '400 bad request' here.
+        if (isReservedRepoName(repositoryName)) {
+            resultHandler.onError(convert(NOT_ALLOWED_REMOVING_META_REPO));
```
Comment (minwoox) [inline server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaServiceImpl.java]: Don't we need to have a new exception or change the name something like `NOT_ALLOWED_MODIFYING_META_REPO`

File: server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProject.java [hunk 2]
```diff
@@ -24,43 +26,146 @@
...
+    private RepositoryManager newRepoManager(File rootDir, Executor repositoryWorker,
+                                             @Nullable RepositoryCache cache) {
         // Enable caching if 'cache' is not null.
         final GitRepositoryManager gitRepos = new GitRepositoryManager(this, rootDir, repositoryWorker);
-        repos = cache == null ? gitRepos : new CachingRepositoryManager(gitRepos, cache);
+        return cache == null ? gitRepos : new CachingRepositoryManager(gitRepos, cache);
+    }
+
+    private void createReservedRepos(long creationTimeMillis, Author author) {
+        if (!repos.exists(Project.REPO_DOGMA)) {
```
Comment (minwoox) [inline server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProject.java]: Can remove all `Project.` in this class?

**Comment by trustin** [comment]
Thanks, reviewers :smile:
