### PR TITLE
Fix flaky test in ZoneAwareMirrorTest

### LINKED ISSUE #1132: Test failure: `com.linecorp.centraldogma.it.mirror.git.ZoneAwareMirrorTest.shouldRunUnpinnedMirrorTaskOnDefaultZone()`
```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1513)
	at org.assertj.core.presentation.StandardRepresentation.representElements(StandardRepresentation.java:681)
	at org.assertj.core.presentation.StandardRepresentation.format(StandardRepresentation.java:658)
	at org.assertj.core.presentation.StandardRepresentation.singleLineFormat(StandardRepresentation.java:583)
	at org.assertj.core.presentation.StandardRepresentation.smartFormat(StandardRepresentation.java:603)
	at org.assertj.core.presentation.StandardRepresentation.toStringOf(StandardRepresentation.java:246)
	at org.assertj.core.presentation.CompositeRepresentation.toStringOf(CompositeRepresentation.java:40)
	at org.assertj.core.error.MessageFormatter.asText(MessageFormatter.java:77)
	at org.assertj.core.error.MessageFormatter.format(MessageFormatter.java:68)
	at org.assertj.core.error.MessageFormatter.format(MessageFormatter.java:61)
	at org.assertj.core.error.BasicErrorMessageFactory.create(BasicErrorMessageFactory.java:107)
	at org.assertj.core.internal.Failures.assertionErrorMessage(Failures.java:144)
	at org.assertj.core.internal.Failures.failure(Failures.java:125)
	at org.assertj.core.internal.CommonValidations.checkSizeGreaterThan(CommonValidations.java:134)
	at org.assertj.core.internal.Iterables.assertHasSizeGreaterThan(Iterables.java:244)
	at org.assertj.core.api.AbstractIterableAssert.hasSizeGreaterThan(AbstractIterableAssert.java:183)
	at com.linecorp.centraldogma.it.mirror.git.ZoneAwareMirrorTest.lambda$shouldRunUnpinnedMirrorTaskOnDefaultZone$5(ZoneAwareMirrorTest.java:149)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

### PR DESCRIPTION
**Pull request by minwoox**
MirrorListener.onX methods can be called by multiple threads: https://github.com/line/centraldogma/blob/e1eaf06745dbecfe009ec1a2fdb405de595acad2/server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/MirrorSchedulingService.java#L167-L168 Thus, we should use thread-safe data structure in the methods.

Close #1132

### CODE REVIEW

File: it/mirror/src/test/java/com/linecorp/centraldogma/it/mirror/git/TestZoneAwareMirrorListener.java [hunk 1]
```diff
@@ -63,13 +64,20 @@ public void onDisallowed(Mirror mirror) {}
     @Override
     public void onStart(MirrorTask mirror) {
         logger.debug("onStart: {}", mirror);
-        startCount.merge(key(mirror), 1, Integer::sum);
+        startCount.compute(key(mirror), (k, v) -> {
+            if (v == null) {
+                return new AtomicInteger(1);
+            } else {
+                v.incrementAndGet();
```
Comment (ikhoon) [inline it/mirror/src/test/java/com/linecorp/centraldogma/it/mirror/git/TestZoneAwareMirrorListener.java:71]: Question) Doesn't `ConcurrentHashMap` provide an atomic update?

**Review by ikhoon — APPROVED** [review]

File: it/mirror/src/test/java/com/linecorp/centraldogma/it/mirror/git/TestZoneAwareMirrorListener.java (hunk 1 above)
Comment (minwoox) [reply it/mirror/src/test/java/com/linecorp/centraldogma/it/mirror/git/TestZoneAwareMirrorListener.java:71]: That's correct. Changed it without much thought. 😓 Let me revert the changes about `startCount`.

**Review by jrhee17 — APPROVED** [review]
