### PR TITLE
Fix to show project creators correctly

### LINKED ISSUE #908: Incorrect Project Creator
The project creators are linked to the creator of the `dogma` repository, which is always the `system`.
https://github.com/line/centraldogma/blob/0fd267dc34209dd60c4ed924bebb047d02550f9a/server/src/main/java/com/linecorp/centraldogma/server/storage/project/Project.java#L62
https://github.com/line/centraldogma/blob/0cf273402d70773e0aab1e2b858111a1c1c0f22c/server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProject.java#L131

### PR DESCRIPTION
**Pull request by minwoox**
Motivation:
The current creator of a project is the creator of the internal `dogma` repository, consistently set as `System`. We should show the correct creator which is stored in the `metadata.json` file.

A noteworthy observation is that only the email of the creator is stored in `metadata.json` instead of the complete `Author` information. A temporary solution involves restoring the `Author` using the email, with plans to revisit this approach if issues arise.

Modifications:
- Fix to show project creators correctly using information stored in the `metadata.json` file.

Result:
- Close #908 
- The project creator is now correctly retrieved based on the information stored in the `metadata.json` file.

### CODE REVIEW

File: server/src/main/java/com/linecorp/centraldogma/server/metadata/UserAndTimestamp.java [hunk 1]
```diff
@@ -89,6 +89,13 @@ public String timestamp() {
         return timestampAsText;
     }
 
+    /**
+     * Returns the epoch milliseconds of the {@link #timestamp()}.
+     */
+    public long epochMillis() {
```
Comment (jrhee17) [inline server/src/main/java/com/linecorp/centraldogma/server/metadata/UserAndTimestamp.java:95]: nit; `timestampMillis` may be a better name since it represents both the field and how it is represented

File: server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProject.java [hunk 2]
```diff
@@ -82,6 +89,14 @@ public class DefaultProject implements Project {
         boolean success = false;
         try {
             createReservedRepos(System.currentTimeMillis());
+            final UserAndTimestamp creation = metadataCreation();
+            if (creation != null) {
```
Comment (jrhee17) [inline server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProject.java:93]: nit; personally I prefer that the branching is done on `REPO_DOGMA` for clarity, but I guess functionally the same is achieved in this block. No problem to leave as-is.

```
    if (REPO_DOGMA.equals(name)) {
        creationTimeMillis = repos.get(REPO_DOGMA).creationTimeMillis();
        author = repos.get(REPO_DOGMA).author();
    } else {
        final UserAndTimestamp creation = metadataCreation(); // fallbacks to Author.SYSTEM
        creationTimeMillis = creation.epochMillis();
        author = Author.ofEmail(creation.user());
    }
```

**Review by jrhee17 — APPROVED** [review]
I understood this PR doesn't have a real user impact (I couldn't find any notion of project author from the UI). Looks good to me 👍 🙇 👍

File: server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProject.java (hunk 2 above)
Comment (minwoox) [reply server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProject.java:93]: I've used the current logic to handle the case when creating metadata fails. (I'm not sure if there's a chance for that event to occur though.)
https://github.com/line/centraldogma/blob/81958a67ac630ee5b306a0229f5b73ce27e6e5d6/server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProject.java#L149-L150
If it fallbacks to Author.SYSTEM in that case, it has to create `Author` again event if it can get it from `repos.get(REPO_DOGMA).author()`. So let me leave it as is. 😉

**Comment by minwoox** [comment]
> I understood this PR doesn't have a real user impact (I couldn't find any notion of project author from the UI).

That is correct for now. 👍

**Review by ikhoon — APPROVED** [review]
Looks good!
