### PR TITLE
Fix equals() implementation in AbstractCommand (#751)

### LINKED ISSUE #751: The equals implementation in AbstractCommand is not correct
Here:
https://github.com/line/centraldogma/blob/c59d2a1defdb7eda3a27959eca0630fd261034cd/server/src/main/java/com/linecorp/centraldogma/server/command/AbstractCommand.java#L62

It says:
```java
        if (!(this instanceof AbstractCommand)) {
            return false;
        }
```

This condition is always false, as `this` is always `AbstractCommand`. It should be instead:
```java
        if (!(obj instanceof AbstractCommand)) {
            return false;
        }
```

It's interesting that IntelliJ IDEA tried to warn about this, but the warning was suppressed with `@SuppressWarnings("EqualsWhichDoesntCheckParameterClass")`. After the fix, the suppression would be unnecessary.

### PR DESCRIPTION
**Pull request by amaembo**
Motivation:
The `equals` method in `AbstractCommand` is not correctly implemented.

Modification:
- Implement `AbstractCommand.equals()` correctly.

Result:
- `ClassCastException` is not raised anymore when checking the equality of sub `AbstractCommand`s that don't override `equals()` method.
- Fixes #751

### CODE REVIEW

**Comment by amaembo** [comment]
Some commands override equals and not affected, but others actually fail with ClassCastException, when comparing with unrelated object. Probably it would be better though to compare classes exactly, instead of instanceof. Like `if (obj == null || obj.getClass() != this.getClass()) return false;`. What do you think?

File: server/src/test/java/com/linecorp/centraldogma/server/command/CreateSessionCommandTest.java [hunk 1]
```diff
@@ -78,4 +80,18 @@ private static String toSerializedBase64(Object object) throws Exception {
...
+        final Session session =
+                new Session("session-id-12345",
+                        "foo",
+                        Instant.EPOCH,
+                        Instant.EPOCH.plus(1, ChronoUnit.MINUTES),
+                        "abc");
+        CreateSessionCommand command = new CreateSessionCommand(1234L,
+                new Author("foo", "bar@baz.com"),
+                session);
+        assertFalse(command.equals("string"));
```
Comment (jrhee17) [inline server/src/test/java/com/linecorp/centraldogma/server/command/CreateSessionCommandTest.java:95]:
```suggestion
        assertThat(command).isNotEqualTo("string")
```

**Review by jrhee17 — APPROVED** [review]
Thanks for finding/fixing this 👍 🙇 🚀

**Comment by jrhee17** [comment]
> Probably it would be better though to compare classes exactly, instead of instanceof. 

Currently, all subclasses perform a check on the class type and the abstract class is package private so I guess it's fine to leave as is 😅

File: server/src/test/java/com/linecorp/centraldogma/server/command/CreateSessionCommandTest.java (hunk 1 above)
Comment (jrhee17) [reply server/src/test/java/com/linecorp/centraldogma/server/command/CreateSessionCommandTest.java:95]: Can you also take a look at lint failures?

**Review by minwoox — APPROVED** [review]
Thanks!
Please address @jrhee17's comment. 😄 
Could you also update the commit description?

**Review by ikhoon — APPROVED** [review]
Thanks, @amaembo!

File: server/src/test/java/com/linecorp/centraldogma/server/command/CreateSessionCommandTest.java (hunk 1 above)
Comment (amaembo) [reply server/src/test/java/com/linecorp/centraldogma/server/command/CreateSessionCommandTest.java]: I addressed the lint failures, thank you. I also updated to use `isNotEqualTo`, though I usually hesitate to do this. It's unclear whether `command.equals("string")` or `"string".equals(command)` (or both) will be called under the hood by testing framework. Here, we want to test the first so if testing framework actually invokes the second, then we would test `String.equals()` method instead. It's ok to use `isNotEqualTo` if you are sure that equality contract is correct, but here the contract is the thing we are testing. Test frameworks usually don't specify how exactly `isNotEqualTo`-like methods work, and behavior may change in future versions of testing frameworks.

I've posted a short twitter thread about this a while ago, you may [want to check](https://twitter.com/tagir_valeev/status/1265482450572136450). Normally, it's recommended to use [EqualsVerifier](https://github.com/jqno/equalsverifier) to check the equality contract, though this would be a much bigger pull request, and likely it will find more problems and I afraid I would not be able to fix all of them with zero experience in this project.

**Comment by amaembo** [comment]
@minwoox updated the commit message. Is it better now?

**Comment by amaembo** [comment]
@minwoox I've updated PR title and commit message, trying to mimic previous commits in master. Should I update anything else?

**Comment by ikhoon** [comment]
> Should I update anything else?

Nope, it looks good.

File: server/src/test/java/com/linecorp/centraldogma/server/command/CreateSessionCommandTest.java (hunk 1 above)
Comment (jrhee17) [reply server/src/test/java/com/linecorp/centraldogma/server/command/CreateSessionCommandTest.java]: My original comment was because if we use `assertj`'s built in method,  we get a richer error message on why the test failed (as opposed to just "`true` isn't equal to `false`")

Having said this, I agree with your point as well. Let me also check out [equalsverifier](https://github.com/jqno/equalsverifier) 🙇

**Comment by minwoox** [comment]
That looks good and thanks a lot for fixing this bug. :smile:
