### PR TITLE
Fix to accept valid ETag values for watch API

### LINKED ISSUE #415: HTTP API - a watch request with a revision number represented as a valid etag must be accepted.
When an HTTP API client sends a watch request, it will send an `If-None-Match` header, e.g.

```
If-None-Match: 3
Prefer: wait=60
```

However, `If-None-Match` must have a valid etag rather than just an integer. It has to be `"3"` or `W/"3"`.

To fix this issue, `WatchRequestConverter` must be updated to handle all three formats:

- `<revision>` (for backward compatibility)
- `"<revision>"`
- `W/"<revision>"`

### PR DESCRIPTION
**Pull request by TheWeaVer**
Motivation:

- `If-None-Match` is often used with `ETag`. Let centraldogma also allow valid `ETag`.

Modifications:

- Parse `ETag` to interpretable `Revision` parameter.

Result:

- Closes #415

### CODE REVIEW

File: server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java [hunk 1]
```diff
@@ -60,11 +60,17 @@ public WatchRequest convertRequest(
             ServiceRequestContext ctx, AggregatedHttpRequest request, Class<?> expectedResultType,
             @Nullable ParameterizedType expectedParameterizedResultType) throws Exception {
 
-        final String ifNoneMatch = request.headers().get(HttpHeaderNames.IF_NONE_MATCH);
+        String ifNoneMatch = request.headers().get(HttpHeaderNames.IF_NONE_MATCH);
         if (isNullOrEmpty(ifNoneMatch)) {
             return null;
         }
 
+        if (ifNoneMatch.startsWith("\"") && ifNoneMatch.endsWith("\"")) {
```
Comment (minwoox) [inline server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java:68]: Could you add a comment that describes the valid three cases?

File: server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverterTest.java [hunk 2]
```diff
@@ -51,6 +51,36 @@ void convertWatchRequest() throws Exception {
         assertThat(watchRequest.timeoutMillis()).isEqualTo(10000); // 10 seconds
     }
 
+    @Test
+    void convertRequestWithETaggedIfNoneMatchHeaderToWatchRequest() throws Exception {
+        final ServiceRequestContext ctx = mock(ServiceRequestContext.class);
+        final AggregatedHttpRequest request = mock(AggregatedHttpRequest.class);
+        final RequestHeaders headers = RequestHeaders.of(HttpMethod.GET, "/",
+                                                         HttpHeaderNames.IF_NONE_MATCH, "\"-1\"",
```
Comment (minwoox) [inline server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverterTest.java:59]: Could you also add cases that are not valid? e.g. `"-1`, `w"-1` etc.

Comment (minwoox) [reply server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverterTest.java:59]: nit: We can create an `HttpRequest` without using `mock`:
```java
HttpRequest request = HttpRequest.of(headers);
ServiceRequestContext.of(request);
```

File: server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverterTest.java [hunk 3]
```diff
@@ -51,6 +51,36 @@ void convertWatchRequest() throws Exception {
...
+        when(request.headers()).thenReturn(headers);
+
+        final WatchRequest watchRequest = convert(ctx, request);
+        assertThat(watchRequest).isNotNull();
+        assertThat(watchRequest.lastKnownRevision()).isEqualTo(Revision.HEAD);
+        assertThat(watchRequest.timeoutMillis()).isEqualTo(10000); // 10 seconds
+    }
+
+    @Test
+    void convertRequestWithWeakComparisonETaggedIfNoneMatchHeaderToWatchRequest() throws Exception {
```
Comment (minwoox) [inline server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverterTest.java:70]: How about just making valid and invalid cases and renaming those to `validIfNoneMatch` and `invalidIfNoneMatch`?

**Review by minwoox — COMMENTED** [review]
Looks good to me. 😄 
Left some minor comments. 😉

File: server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverterTest.java (hunk 2 above)
Comment (TheWeaVer) [reply server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverterTest.java:59]: `convertRequest` requires `AggregatedHttpRequest` and `ServiceRequestContext`. `ServiceRequestContext` requires `HttpRequest`. Is there a way creating `ServiceRequestContext` with `AggregatedHttpRequest`?

File: server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java (hunk 1 above)
Comment (TheWeaVer) [reply server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java:68]: I add javadoc like:
```
    /**
     * Converts the specified {@code request} to a {@link WatchRequest} when the request has
     * {@link HttpHeaderNames#IF_NONE_MATCH}. {@code null} otherwise.
     *
     * {@link HttpHeaderNames#IF_NONE_MATCH} must be integer, ETag and Weak Comparison ETag.
     */
```

File: server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverterTest.java (hunk 2 above)
Comment (TheWeaVer) [reply server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverterTest.java:59]: Hmm... Seems like it..+_+
```java
final HttpRequest request = HttpRequest.of(headersWithSmallCase);
final ServiceRequestContext serviceRequestContext = ServiceRequestContext.of(request);
final WarchRequest warchRequest = convert(ctx, (AggregatedHttpRequest) request);
```

Comment (minwoox) [reply server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverterTest.java]: We can do:
```java
final AggregatedHttpRequest request = AggregatedHttpRequest.of(headers);
final ServiceRequestContext ctx = ServiceRequestContext.of(request.toHttpRequest());
```
When we implement this class, we didn't have `ServiceRequestContext.of(...)` so we used mock. 😅 
Sorry about it, and thanks for changing it. 😆

File: server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverterTest.java [hunk 4]
```diff
@@ -37,18 +39,92 @@
...
+                                  HttpHeaderNames.IF_NONE_MATCH, "\"-1",
+                                  HttpHeaderNames.PREFER, "wait=10");
+        final HttpRequest fifthInvalidRequest = HttpRequest.of(fifthInvalidHeaders);
+        final ServiceRequestContext fifthCtx = ServiceRequestContext.of(fifthInvalidRequest);
+
+        assertThatThrownBy(() -> convert(fifthCtx, fifthInvalidRequest.aggregate().join()))
+                .isInstanceOf(IllegalArgumentException.class);
     }
 
     @Test
```
Comment (minwoox) [inline server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverterTest.java:130]: Could you also fix this test as well? 😆

Comment (TheWeaVer) [reply server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverterTest.java:128]: Applied!

File: server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverterTest.java (hunk 2 above)
Comment (TheWeaVer) [reply server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverterTest.java]: Thank you 😄 I applied it.

File: server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java (hunk 1 above)
Comment (minwoox) [reply server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java:70]: It's not an integer it also can be a String such as `head` or `init`.
Instead of adding it to Javadoc, how about adding just comments so that reviewers easily notice the valid cases?
```java
// Thee below cases are valid:
// - <revision> (for backward compatibility)
// - "<revision>"
// - W/"<revision>"
```

File: server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java [hunk 5]
```diff
@@ -60,11 +60,17 @@ public WatchRequest convertRequest(
...
+            ifNoneMatch = ifNoneMatch.substring(1, ifNoneMatch.length() - 1);
+        } else if (ifNoneMatch.startsWith("W/\"") && ifNoneMatch.endsWith("\"")) {
```
[the remark this answers is not in the document]
Comment (ikhoon) [reply server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java:72]: How about extracting this block as a package-private method like `extractRevision(ifNoneMatch)` and adding unit tests for it?

[the remark this answers is not in the document]
Comment (TheWeaVer) [reply server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java]: > How about extracting this block as a package-private method like extractRevision(ifNoneMatch) and adding unit tests for it?

Then, is it better to throw `IllegalArgumentException`, if the `ifNoneMatch` is not matched with `<revision`> , `"<revision>"` or `W/"<revision>"`?

File: server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java [hunk 6]
```diff
@@ -81,6 +81,21 @@ public WatchRequest convertRequest(
         return new WatchRequest(lastKnownRevision, timeoutMillis, notifyEntryNotFound);
     }
 
+    String extractRevision(String ifNoneMatch) {
+        // Three below cases are valid:
+        // - <revision> (for backward compatibility)
+        // - "<revision>"
+        // - W/"<revision>"
+        if (ifNoneMatch.startsWith("\"") && ifNoneMatch.endsWith("\"") && !ifNoneMatch.equals("\"")) {
```
Comment (minwoox) [inline server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java:89]: How about?
```java
if (ifNoneMatch.length() > 1 && ifNoneMatch.charAt(0) == '"' &&
    ifNoneMatch.charAt(ifNoneMatch.length() - 1) == '"') {
    return ...
}

if (ifNoneMatch.length() > 2 && ifNoneMatch.startsWith("W/\"") &&
    ifNoneMatch.charAt(ifNoneMatch.length() - 1) == '"') {
    return ...
}
```

Comment (TheWeaVer) [reply server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java:89]: More simple 🙂

Comment (TheWeaVer) [reply server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java]: And to handle, `""` I revise condition `ifNoneMatch.length() > 1` to `ifNoneMatch.length() > 2`.

File: server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java [hunk 7]
```diff
@@ -81,6 +81,24 @@ public WatchRequest convertRequest(
         return new WatchRequest(lastKnownRevision, timeoutMillis, notifyEntryNotFound);
     }
 
+    String extractRevision(String ifNoneMatch) {
```
Comment (ikhoon) [inline server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java:84]:
```suggestion
    @VisibleForTesting
    String extractRevision(String ifNoneMatch) {
```

**Review by ikhoon — APPROVED** [review]
Thanks, @TheWeaVer!

File: server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java (hunk 7 above)
Comment (TheWeaVer) [reply server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java:84]: I'm sorry but, is there a reason to annotate `@VisibleForTesting`?.?

Comment (minwoox) [reply server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java:84]: @TheWeaVer
To tell the reviewers that this method is only used by tests so we didn't make it private.  😄

Comment (TheWeaVer) [reply server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java:84]: Ah.. I see. To announce that why this API can not be `private`. 🙂

**Comment by minwoox** [comment]
Oops, could you import `@VisibleForTesting`?
https://github.com/line/centraldogma/runs/4613486851?check_suite_focus=true#step:5:32

**Comment by minwoox** [comment]
https://github.com/line/centraldogma/runs/4614973923?check_suite_focus=true#step:5:188
Oops, could you check it again? 😆

**Comment by TheWeaVer** [comment]
Ouch.. @minwoox resolved..!

File: server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java [hunk 8]
```diff
@@ -81,6 +82,25 @@ public WatchRequest convertRequest(
...
+        // - "<revision>"
+        // - W/"<revision>"
+        if (ifNoneMatch.length() > 2 && ifNoneMatch.charAt(0) == '"' &&
+            ifNoneMatch.charAt(ifNoneMatch.length() - 1) == '"') {
+            return ifNoneMatch.substring(1, ifNoneMatch.length() - 1);
+        }
+
+        if (ifNoneMatch.length() > 4 && ifNoneMatch.startsWith("W/\"") &&
+            ifNoneMatch.charAt(ifNoneMatch.length() - 1) == '"') {
+            return ifNoneMatch.substring(3, ifNoneMatch.length() - 1);
```
Comment (ikhoon) [inline server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java:98]: nit: Extract `ifNoneMatch.length()` as a local variable? It is used in multiple places.

Comment (TheWeaVer) [reply server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java]: @ikhoon , thank you. I revised. 🙂

File: server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverterTest.java [hunk 9]
```diff
@@ -17,47 +17,76 @@
...
+        final String secondIfNoneMatch = "\"-1\"";
+        final String secondRevision = converter.extractRevision(secondIfNoneMatch);
+        assertThat(secondRevision).isEqualTo("-1");
+
+        final String thirdIfNoneMatch = "W/\"-1\"";
+        final String thirdRevision = converter.extractRevision(thirdIfNoneMatch);
+        assertThat(thirdRevision).isEqualTo("-1");
+    }
+
+    @Test
```
Comment (jrhee17) [inline server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverterTest.java:50]: optional; seems like a missed opportunity to use `@ParameterizedTest`

**Review by jrhee17 — APPROVED** [review]
💯 for me! Thank you @TheWeaVer ! 🙇 🎉 🥳

**Comment by minwoox** [comment]
Thanks! Happy new year, @TheWeaVer! 😄
